- name: Service template is rendered
  template:
    src: service.j2
    dest: "/etc/systemd/system/{{ ansible_play_name }}.service"
    mode: "0664"
  become: true
  tags: systemd, service

- name: Config changes are picked up by systemd
  systemd:
    daemon_reload: yes
  become: true
  tags: systemd, service

- name: Service is restarted
  systemd:
    name: "{{ ansible_play_name }}.service"
    enabled: true
    state: restarted
  become: true
  tags: systemd, service
