- name: Dependencies are installed
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - jq
      - sqlite3
      - zstd
  tags: [ apt ]

- name: b2 tool is present
  get_url:
    url: https://github.com/Backblaze/B2_Command_Line_Tool/releases/download/v3.4.0/b2-linux
    dest: "/usr/local/bin/b2"
    mode: "0755"

- name: sqlite-backup-b2 tool is present
  template:
    src: sqlite-backup-b2.j2
    dest: /usr/local/bin/sqlite-backup-b2
    mode: "0755"

- name: Backup service is present
  template:
    src: service.j2
    dest: "/etc/systemd/system/{{ ansible_play_name }}-backup.service"
    mode: "0664"
  register: service_rendered
  tags: [ systemd, timer ]

- name: Backup service is enabled
  systemd:
    name: "{{ ansible_play_name }}-backup.service"
    enabled: true
    daemon_reload: true
  tags: [ systemd, service ]

- name: Backup timer is present
  template:
    src: timer.j2
    dest: "/etc/systemd/system/{{ ansible_play_name }}-backup.timer"
    mode: "0664"
  tags: [ systemd, timer ]

- name: Backup timer is enabled
  systemd:
    name: "{{ ansible_play_name }}-backup.timer"
    enabled: true
    daemon_reload: true
  tags: [ systemd, timer ]
